### ISSUE TITLE
1.0.9 - version code in .apk needs updating

### ISSUE THREAD

**Issue by DiagonalArg** [naoxio/inner_breeze#17]
Please see here:

https://github.com/ImranR98/Obtainium/issues/1091#issuecomment-1815800125

**Comment by waotzi** [comment]
@DiagonalArg Hi :smile: 

I see, yeah I didn't update the version, because it was just a quick desktop version fix and thought it wouldn't be necessary to update the android version which would be triggered by the version update, but i see now that this causes more confusion.

I updated the app now and I'll keep the version up to date from now on :+1: 

![photo_2023-11-18_11-00-46](https://github.com/naoxio/inner_breeze/assets/31371807/deab5eaa-2dea-45e2-8bfd-a8f6dc61e48d)

**Comment by DiagonalArg** [comment]
Much appreciated.  And thank you for all your work.
